# Generated by Django 3.2.15 on 2022-09-14 07:54

import backend.common
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cctvs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chlid_class', models.TextField()),
                ('cctv', models.ManyToManyField(null=True, related_name='child_cctv', to='cctvs.CCTV')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_img', models.FileField(upload_to=backend.common.file_upload_path)),
                ('time', models.DateTimeField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missingchilds.child')),
            ],
        ),
    ]
