# Generated by Django 3.2.15 on 2022-09-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('top_category', models.CharField(max_length=50)),
                ('top_color', models.CharField(max_length=50)),
                ('bottom_category', models.CharField(max_length=50)),
                ('bottom_color', models.CharField(max_length=50)),
                ('belonging', models.CharField(max_length=50)),
                ('pet', models.CharField(max_length=50)),
                ('video_url', models.CharField(max_length=50)),
                ('activation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_img', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('place', models.CharField(max_length=50)),
                ('activation', models.BooleanField(max_length=50)),
            ],
        ),
    ]
