# Generated by Django 3.2.15 on 2022-09-14 07:54

import backend.common
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('detection_class', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_img', models.FileField(upload_to=backend.common.file_upload_path)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('result_class', models.CharField(max_length=5)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='uploads.upload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChildData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_class', models.TextField()),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.upload')),
            ],
        ),
    ]
