# Generated by Django 3.2.15 on 2022-09-13 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_class', models.CharField(max_length=5)),
                ('video_url', models.URLField()),
                ('activation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_img', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('place', models.CharField(max_length=30)),
                ('result_class', models.CharField(max_length=5)),
                ('activation', models.BooleanField()),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safetys.upload')),
            ],
        ),
    ]
